FORMAT: 1A
HOST: https://mylyst.herokuapp.com/v1

# Mylyst

Everyday, there's this list of things you dream of doing before you pass on.

- Dreams you wish to fulfil
- Ideas you wish to implement
- Friends you wish to make
- Cars you wish to drive
- Places you wish to go

**What a life of wishes, really**

> The bucketlist service may not be a genie to do "pooof" and all your wishes will
appear, but a service that enables you to create this list of things you want to
do, categorize them under a bucketlist and mark it's status.



## User Resource [/users]

### Create A New User [POST]

As a bit of helper, there's an additional endpoint that allows you to
create an account to access the bucketlist API service. Make a POST
request with {name, email, password}. If you get an error message,
check that the email you are using is valid and be sure it has not
been used by another user.

+ Request (application/json)
    
    + Body
    
            {
                "name": "Bucketlist User",
                "email": "user@bucketlist.com",
                "password": "bucketlistuser"
            }

+ Response 204 (application/json)


## Login Authorization [/auth/login]

### Login To Get a User Token [POST]

Provided you are a registered user, you can login at any time, by making a 
POST request to the (/auth/login) route passing {name, password} to get a unique
token, with which you can use to make all other authorized request on the platform

+ Request (application/json)
    
    + Body
    
            {
                "email": "user@bucketlist.com",
                "password": "bucketlistuser"
            }

+ Response 200 (application/json)

    + Body
    
            {
              email: "user@bucketlist.com",
              name: "bucketlistuser",
              token: {TOKEN},
              login_status: "logged_in"
            }

## Logout Authorization [/auth/logout]

### Logout to Deauthorize A Token [GET]
Once you have completed all that you need to do with the service, you can
deauthorize the token by making a GET request to the logout (/auth/logout)
route with valid token set in the header.

+ Request (application/json)

    + Header
    
            Authorization: Token token={TOKEN}
            
+ Response 200 (application/json)

    + Body
            
            {
              message: "You were successfully logged out!"
            }


## Bucketlist Collection [/bucketlists]

### Gets All Bucketlists [GET]

You can get view all bucketlists {id, name} when you call the /bucketlists route

+ Response 200 (application/json)

        [
            {
             id: 1,
             name: “BucketList1”
            },
            {
             id: 2,
             name: “BucketList2”
            },
            {
             id: 3,
             name: “BucketList3”
            },
            {
             id: 4,
             name: “BucketList4”
            }
            
        ]

### Create a New Bucketlist [POST]

You may create a new bucketlist by making a post request to the /bucketlists
route. Important params to pass is the name of the bucketlist you wish to create

+ Request (application/json)

       + Header
            
            Authorization: Token token={TOKEN}
       
       
       + Body
       
            {
                "name": "Things I want to do next year"
            }
     
+ Response 201 (application/json)

    + Headers

            Location: /bucketlists/12

    + Body

            {
             id: 12,
             name: “Things I want to do next year”,
             items: [],
             date_created: “2015-08-12 11:57:23”,
             date_modified: “2015-08-12 11:57:23”,
             created_by: “1113456”
            }
            
## Bucketlist [/bucketlists/{id}]

### Get a Specific Bucketlist [GET]

Provided you have a valid token you can make a call to the Bucketlist "/bucketlist/:id"
To get the full resource information on a particular bucketlist

+ Request

    + Headers
    
            Authorization: Token token={TOKEN}

+ Parameters
    + id: `1` (number, required) - The id of the bucketlist in the form of a number
        
        
+ Response 200 (application/json)

    + Headers
    
            Location: /bucketlists/12

    + Body

            {
             id: 12,
             name: “Things I want to do next year”,
             items: [
                {
                    id: 1,
                    name: “I need to do X”,
                    date_created: “2015-08-12 11:57:23”,
                    date_modified: “2015-08-12 11:57:23”,
                    done: False
                }
             ],
             date_created: “2015-08-12 11:57:23”,
             date_modified: “2015-08-12 11:57:23”,
             created_by: “1113456”
            }


### Create a New Bucketlist Item [POST]

Provided you have a valid token you can create a new bucketlist item under the id
specified passing the required parameters {name, status} of the item to be created

+ Request (application/json)

    + Headers
    
            Authorization: Token token={TOKEN}
            
    + Body

            {
                "name": "I want to sky dive across the Niagara Falls",
                "status": 1
            }

+ Parameters
    + id: `12` (number, required) - The id of the bucketlist in the form of a number
   
    
+ Response 201 (application/json)

    + Body
        
            {
             id: 12,
             name: “Things I want to do next year”,
             items: [
                {
                    id: 1,
                    name: “I need to do X”,
                    date_created: “2015-08-12 11:57:23”,
                    date_modified: “2015-08-12 11:57:23”,
                    done: False
                }
             ],
             date_created: “2015-08-12 11:57:23”,
             date_modified: “2015-08-12 11:57:23”,
             created_by: “1113456”
            }
       
            
### Update a Bucketlist [PUT]
At times you want to edit the name of your bucketlist, say for example you
want to change from "Bucketlist for next month" to "Bucketlist for the
next 5 years". You can make a PUT request passing the id of the resource
you wish to change and the update data. This action is only permitted
if you created this bucketlist

+ Request (application/json)
    
    + Header
            
            Authorization: Token token={TOKEN}

    + Body
            
            {
                "name": "Bucketlist for the next 5 years"
            }

+ Parameters
    + id: `13` (number, required) - The id of the bucketlist in the form of a number
   
    

+ Response 204 (application/json)

    + Header
    
            Content-length: 0
            
### Delete a Bucketlist [DELETE]
Say, you have to delete a bucketlist, you can make a DELETE request to the API
endpoint with a valid token, provided you created the bucketlist

+ Request (application/json)

    + Header
        
            Authorization: Token token={TOKEN}
            
+ Parameters
    + id: `13` (number, required) - The id of the bucketlist in the form of a number
   
+ Response 204 (application/json)

    + Header
    
            Content-length: 0